

const ADD_NEW_OFFER=1014;
const CLOSED_AUCTION_SUCCESSFULLY=1015;
const SIGN_UP_SUCCESSFULLY=1016;
const UPDATED_USER_CREDIT_SUCCESSFULLY=1017;
const ADD_NEW_OFFER_TO_AUCTION="1";
const AUCTION_WAS_CLOSED="2";


export {ADD_NEW_OFFER,CLOSED_AUCTION_SUCCESSFULLY,SIGN_UP_SUCCESSFULLY,AUCTION_WAS_CLOSED,ADD_NEW_OFFER_TO_AUCTION,UPDATED_USER_CREDIT_SUCCESSFULLY} ;
